sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "lts/*"
env:
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
script: npm run-script $TEST_SUITE
